function Timingarray = Importdesfile(filename)
%IMPORTFILE1 Import data from a text file
%  OPOFMRI34V3 = IMPORTFILE1(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  OPOFMRI34V3 = IMPORTFILE1(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  OPOfMRI34V3 = importfile1("/Users/filip/Downloads/OPO_fMRI_34_V3.txt", [2, 2]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 11-Jun-2020 15:00:19

%% Input handling
dataLines=[2 2; 8 8; 11 11; 17 17; 20 20; 23 23];

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 46);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["Onset", "Start", "Stimulation", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8", "VarName9", "VarName10", "VarName11", "VarName12", "VarName13", "VarName14", "VarName15", "VarName16", "VarName17", "VarName18", "VarName19", "VarName20", "VarName21", "VarName22", "VarName23", "VarName24", "VarName25", "VarName26", "VarName27", "VarName28", "VarName29", "VarName30", "VarName31", "VarName32", "VarName33", "VarName34", "VarName35", "VarName36", "VarName37", "VarName38", "VarName39", "VarName40", "VarName41", "VarName42", "VarName43", "VarName44", "VarName45", "VarName46"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, "Onset", "TrimNonNumeric", true);
opts = setvaropts(opts, "Onset", "ThousandsSeparator", ",");

% Import the data
Timingarray = readtable(filename, opts);

%% Convert to output type
Timingarray = table2array(Timingarray);
end